-- MySQL Script generated by MySQL Workbench
-- Fri Oct 10 22:17:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WellAll_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WellAll_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WellAll_db` DEFAULT CHARACTER SET utf8 ;
USE `WellAll_db` ;

-- -----------------------------------------------------
-- Table `WellAll_db`.`patients_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WellAll_db`.`patients_table` (
  `PatientID` INT NOT NULL AUTO_INCREMENT,
  `PatientBarcodeID` VARCHAR(50) NOT NULL,
  `PatientFirstName` VARCHAR(100) NOT NULL,
  `PatientLastName` VARCHAR(100) NOT NULL,
  `PatientDateOfBirth` DATE NOT NULL,
  `PatientGender` VARCHAR(10) NULL DEFAULT NULL,
  `PatientContactNumber` VARCHAR(20) NULL DEFAULT NULL,
  `PatientAddress` VARCHAR(255) NULL DEFAULT NULL,
  `PatientBloodType` VARCHAR(10) NULL DEFAULT NULL,
  `PatientAllergies` VARCHAR(45) NULL DEFAULT NULL,
  `PatientExistingConditions` VARCHAR(45) NULL DEFAULT NULL,
  `PatientEmergencyContact` VARCHAR(200) NULL DEFAULT NULL,
  `PatientEmergencyPhone` VARCHAR(20) NULL DEFAULT NULL,
  `PatientDateRegistered` DATE NULL,
  PRIMARY KEY (`PatientID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WellAll_db`.`doctors_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WellAll_db`.`doctors_table` (
  `DoctorID` INT NOT NULL AUTO_INCREMENT,
  `DoctorBarcode` VARCHAR(50) NOT NULL,
  `DoctorFirstName` VARCHAR(100) NOT NULL,
  `DoctorLastName` VARCHAR(100) NOT NULL,
  `Specialization` VARCHAR(100) NULL DEFAULT NULL,
  `DoctorContactNumber` VARCHAR(20) NULL DEFAULT NULL,
  `DoctorEmail` VARCHAR(100) NULL DEFAULT NULL,
  `DoctorAddress` VARCHAR(255) NULL DEFAULT NULL,
  `DoctorDateRegistered` DATE NULL DEFAULT NULL,
  `DoctorAvailability` VARCHAR(150) NULL,
  PRIMARY KEY (`DoctorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WellAll_db`.`appointments_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WellAll_db`.`appointments_table` (
  `AppointmentID` INT NOT NULL AUTO_INCREMENT,
  `PatientID` INT NOT NULL,
  `DoctorID` INT NOT NULL,
  `AppointmentBarcodeID` VARCHAR(50) NOT NULL,
  `AppointmentDate` DATE NULL DEFAULT NULL,
  `AppointmentTime` TIME NULL DEFAULT NULL,
  `Reason` TEXT NULL DEFAULT NULL,
  `DateCreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AppointmentID`),
  UNIQUE INDEX `AppointmentBarcodeID_UNIQUE` (`AppointmentBarcodeID` ASC) VISIBLE,
  INDEX `fk_appointments_table_patients_table_idx` (`PatientID` ASC) VISIBLE,
  INDEX `fk_appointments_table_doctors_table1_idx` (`DoctorID` ASC) VISIBLE,
  CONSTRAINT `fk_appointments_table_patients_table`
    FOREIGN KEY (`PatientID`)
    REFERENCES `WellAll_db`.`patients_table` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_table_doctors_table1`
    FOREIGN KEY (`DoctorID`)
    REFERENCES `WellAll_db`.`doctors_table` (`DoctorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WellAll_db`.`check_in_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WellAll_db`.`check_in_table` (
  `CheckInID` INT NOT NULL AUTO_INCREMENT,
  `PatientID` INT NOT NULL,
  `DoctorID` INT NOT NULL,
  `AppointmentID` INT NOT NULL,
  `CheckInTime` DATETIME NOT NULL,
  `CheckInRemarks` TEXT NULL DEFAULT NULL,
  `CheckInDateCreated` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`CheckInID`),
  INDEX `fk_check_in_table_patients_table1_idx` (`PatientID` ASC) VISIBLE,
  INDEX `fk_check_in_table_doctors_table1_idx` (`DoctorID` ASC) VISIBLE,
  INDEX `fk_check_in_table_appointments_table1_idx` (`AppointmentID` ASC) VISIBLE,
  CONSTRAINT `fk_check_in_table_patients_table1`
    FOREIGN KEY (`PatientID`)
    REFERENCES `WellAll_db`.`patients_table` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_check_in_table_doctors_table1`
    FOREIGN KEY (`DoctorID`)
    REFERENCES `WellAll_db`.`doctors_table` (`DoctorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_check_in_table_appointments_table1`
    FOREIGN KEY (`AppointmentID`)
    REFERENCES `WellAll_db`.`appointments_table` (`AppointmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WellAll_db`.`medical_records_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WellAll_db`.`medical_records_table` (
  `medicalID` INT NOT NULL AUTO_INCREMENT,
  `PatientID` INT NOT NULL,
  `DoctorID` INT NOT NULL,
  `diagnosis` TEXT NULL DEFAULT NULL,
  `treatment` TEXT NULL DEFAULT NULL,
  `prescription` TEXT NULL DEFAULT NULL,
  `MedicalDateRegistered` DATE NULL,
  PRIMARY KEY (`medicalID`),
  INDEX `fk_medical_records_table_patients_table1_idx` (`PatientID` ASC) VISIBLE,
  INDEX `fk_medical_records_table_doctors_table1_idx` (`DoctorID` ASC) VISIBLE,
  CONSTRAINT `fk_medical_records_table_patients_table1`
    FOREIGN KEY (`PatientID`)
    REFERENCES `WellAll_db`.`patients_table` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_records_table_doctors_table1`
    FOREIGN KEY (`DoctorID`)
    REFERENCES `WellAll_db`.`doctors_table` (`DoctorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
