-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 18:11:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WellAll_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WellAll_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WellAll_db` DEFAULT CHARACTER SET utf8 ;
USE `WellAll_db` ;

-- -----------------------------------------------------
-- Table `WellAll_db`.`patient_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WellAll_db`.`patient_table` (
  `PatientID` INT NOT NULL AUTO_INCREMENT,
  `BarcodeID` VARCHAR(50) NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Gender` VARCHAR(10) NULL,
  `ContactNumber` VARCHAR(20) NULL,
  `Address` VARCHAR(255) NULL,
  `BloodType` VARCHAR(10) NULL,
  `Allergies` VARCHAR(45) NULL,
  `ExistingConditions` VARCHAR(45) NULL,
  `EmergencyContact` VARCHAR(100) NULL,
  `EmergencyPhone` VARCHAR(20) NULL,
  `DateRegistered` DATE NULL,
  PRIMARY KEY (`PatientID`),
  UNIQUE INDEX `BarcodeID_UNIQUE` (`BarcodeID` ASC) VISIBLE)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `doctor_table` (
  `DoctorID` INT NOT NULL AUTO_INCREMENT,
  `DoctorCode` VARCHAR(50) NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `Specialization` VARCHAR(100) NULL,
  `ContactNumber` VARCHAR(20) NULL,
  `Email` VARCHAR(100) NULL,
  `Address` VARCHAR(255) NULL,
  `DateRegistered` DATE NULL,
  PRIMARY KEY (`DoctorID`),
  UNIQUE INDEX `DoctorCode_UNIQUE` (`DoctorCode` ASC) VISIBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
